/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaylistRecommendationRouteImport } from './routes/playlist-recommendation'
import { Route as IndexRouteImport } from './routes/index'

const PlaylistRecommendationRoute = PlaylistRecommendationRouteImport.update({
  id: '/playlist-recommendation',
  path: '/playlist-recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playlist-recommendation': typeof PlaylistRecommendationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playlist-recommendation': typeof PlaylistRecommendationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playlist-recommendation': typeof PlaylistRecommendationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/playlist-recommendation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playlist-recommendation'
  id: '__root__' | '/' | '/playlist-recommendation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaylistRecommendationRoute: typeof PlaylistRecommendationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playlist-recommendation': {
      id: '/playlist-recommendation'
      path: '/playlist-recommendation'
      fullPath: '/playlist-recommendation'
      preLoaderRoute: typeof PlaylistRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaylistRecommendationRoute: PlaylistRecommendationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
